# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.23.4
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nirvana/.conda/envs/Laba1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', No

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
v0 = np.zeros(10)
print(v0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
arr = np.array([1, 2, 3, 4]) 
print("Memory size of array:", arr.nbytes)

Memory size of array: 16


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
v0 = np.zeros(10)
v0[4] = 1
print(v0)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print("Reverse vector: ")
v = v[::-1]
print(v)

Reverse vector: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
matr3x3 = np.arange(0, 9).reshape(3,3)
print(matr3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
matr3x3=np.identity(3)
print(matr3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
arr3x3x3 = np.random.random((3,3,3))
print(arr3x3x3)

[[[0.74846811 0.83241738 0.91178281]
  [0.36533451 0.2118973  0.97609447]
  [0.92852714 0.39848513 0.95684669]]

 [[0.82387723 0.28575299 0.89492866]
  [0.96349127 0.86026852 0.20388304]
  [0.20786189 0.53434339 0.20221257]]

 [[0.36109601 0.75271789 0.64611837]
  [0.22993581 0.08790013 0.09476463]
  [0.49391694 0.32610349 0.92260488]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
arr10x10 = np.random.random((10,10))
arr10x10

array([[0.04198073, 0.58656114, 0.6086578 , 0.52559941, 0.25512683,
        0.77195906, 0.24167966, 0.69413054, 0.69959507, 0.55876387],
       [0.1772835 , 0.41788312, 0.907852  , 0.95244182, 0.92724486,
        0.51871291, 0.98486805, 0.4572136 , 0.65149883, 0.18422085],
       [0.7896492 , 0.84498508, 0.1109958 , 0.16253471, 0.06033849,
        0.90310613, 0.49453763, 0.69811941, 0.31133965, 0.2808449 ],
       [0.98691555, 0.67809039, 0.63921454, 0.36854405, 0.71859527,
        0.25275329, 0.85687134, 0.82096564, 0.14873471, 0.94931004],
       [0.17243695, 0.58774175, 0.9525473 , 0.17994521, 0.17735112,
        0.85162738, 0.02018476, 0.69199214, 0.53947602, 0.29037482],
       [0.01635365, 0.89331985, 0.29661385, 0.04244336, 0.98190763,
        0.24112329, 0.9484405 , 0.14244956, 0.07678337, 0.66215459],
       [0.98611639, 0.02736836, 0.71516073, 0.76430787, 0.02454547,
        0.43130676, 0.19770388, 0.76174758, 0.95263815, 0.41071831],
       [0.61261165, 0.95621079, 0.2486985

In [26]:
arr_min = arr10x10.min()
arr_max = arr10x10.max()
print("min: ", arr_min)
print("max: ", arr_max)

min:  0.012907190646901157
max:  0.9869155540320571


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
v = np.random.random(30)
v

array([0.52117281, 0.85475492, 0.33779472, 0.54274253, 0.47562334,
       0.98268903, 0.74198414, 0.04878281, 0.64994012, 0.25044704,
       0.4411962 , 0.92459028, 0.8733303 , 0.81552795, 0.51728135,
       0.75717205, 0.59531895, 0.84532205, 0.63958325, 0.36786256,
       0.95608645, 0.24970568, 0.26433089, 0.52415514, 0.26697551,
       0.15261347, 0.70297113, 0.61385656, 0.33676921, 0.34088929])

In [29]:
print(v.mean())

0.553048990183084


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
arr2d = np.ones((5, 5))
arr2d[1:-1,1:-1]=0
print(arr2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [36]:
a = np.ones((4, 4))
b = np.pad(array = a, pad_width = 1, mode = 'constant')
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
0 * np.nan 

nan

In [4]:
np.nan == np.nan

False

In [5]:
np.inf > np.nan

False

In [6]:
np.nan - np.nan

nan

In [7]:
np.nan in set([np.nan])

True

In [10]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [40]:
x = np.array([1, 2, 3, 4])
np.diag(1 + np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [60]:
x = np.zeros((8, 8))
x[0::2,0::2] = 1
x[1::2,1::2] = 1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [44]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [70]:
matr8x8 = np.array([[1,0], [0,1]])
matr8x8 = np.tile(matr8x8,(4,4))
print(matr8x8)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [76]:
matr5x5 = np.random.random((5,5))
matr5x5

array([[0.83972001, 0.87665583, 0.89548486, 0.3813927 , 0.32585869],
       [0.55558129, 0.85187524, 0.5995919 , 0.1217175 , 0.5801201 ],
       [0.8064225 , 0.12506364, 0.7931918 , 0.41143081, 0.36546225],
       [0.72699436, 0.36083571, 0.94319794, 0.81211818, 0.38658969],
       [0.25238164, 0.3944691 , 0.43097028, 0.1343665 , 0.27178116]])

In [81]:
matr_max = matr5x5.max() 
matr_min = matr5x5.min()
matr5x5 = (matr5x5 - matr_min)/(matr_max - matr_min)
print(matr5x5)

[[0.87403482 0.91899732 0.94191817 0.31610637 0.24850402]
 [0.52814865 0.88883155 0.5817234  0.         0.5580201 ]
 [0.83350128 0.0040733  0.81739535 0.35267218 0.29671399]
 [0.73681225 0.29108204 1.         0.84043472 0.32243274]
 [0.15905934 0.33202446 0.37645786 0.01539781 0.18267466]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [86]:
customDType = np.dtype([("r", np.ubyte, (1,)), ("g", np.ubyte, (1,)), ("b", np.ubyte, (1,)), ("a", np.ubyte, (1,))])
customDType

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [89]:
matr5x3 = np.random.random((5,3))
matr5x3

array([[0.5706552 , 0.35188326, 0.42149456],
       [0.36758246, 0.10673514, 0.28325055],
       [0.95429574, 0.60330727, 0.6099734 ],
       [0.65936193, 0.89657955, 0.71118497],
       [0.52403103, 0.7867996 , 0.66458414]])

In [90]:
matr3x2 = np.random.random((3,2))
matr3x2

array([[0.78710299, 0.86570478],
       [0.51032253, 0.03630722],
       [0.92547706, 0.48545535]])

In [93]:
mult_matr = np.dot(matr5x3, matr3x2)
mult_matr

array([[1.01882191, 0.71141163],
       [0.60593649, 0.45959865],
       [1.62352672, 1.14415765],
       [1.63471587, 0.94861364],
       [1.42904533, 0.8048486 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [96]:
arr1d = np.arange(1, 10)
arr1d[(arr1d > 3) & (arr1d < 8)] *= -1
arr1d

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [97]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [11]:
Z = np.arange(1,5)
print(Z)
Z ** Z

[1 2 3 4]


array([  1,   4,  27, 256])

In [100]:
2 << Z >> 2

array([1, 2, 4, 8], dtype=int32)

In [101]:
Z <- Z

array([False, False, False, False])

In [102]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [103]:
Z/1/1

array([1., 2., 3., 4.])

In [106]:
Z<Z>Z #not legal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [107]:
np.array(0) / np.array(0)

C:\Users\Nirvana\AppData\Local\Temp\ipykernel_10600\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [108]:
np.array(0) // np.array(0)

C:\Users\Nirvana\AppData\Local\Temp\ipykernel_10600\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [109]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [111]:
arr = np.array([1.234, 12.34, 123.4, 1234])
arr

array([   1.234,   12.34 ,  123.4  , 1234.   ])

In [114]:
np.round(arr,0)

array([1.000e+00, 1.200e+01, 1.230e+02, 1.234e+03])

#### 30. How to find common values between two arrays? (★☆☆)

In [115]:
np.intersect1d([123, 132, 213, 231], [123, 321])

array([123])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [116]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [117]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [119]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2022-12-04')

In [122]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2022-12-05')

In [123]:
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tomorrow

numpy.datetime64('2022-12-06')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [126]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [134]:
A = np.ones(1) * 1
B = np.ones(1) * 1
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [12]:
arr = np.array([1.2345, 12.345, 123.45, 1234.5])

In [16]:
arr.astype(np.int32)

array([   1,   12,  123, 1234])

In [17]:
arr.astype(int)

array([   1,   12,  123, 1234])

In [14]:
np.int_(arr)

array([   1,   12,  123, 1234])

In [15]:
arr.astype(np.int64)

array([   1,   12,  123, 1234], dtype=int64)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [143]:
matr5x5 = np.zeros((5,5))
matr5x5 += np.arange(5)
matr5x5

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [144]:
def generate():
   for n in range(10):
       yield n
arr = np.fromiter(generate(),dtype=float,count=-1)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [150]:
v = np.linspace(0,1,12,endpoint=True)[1:-1]
v

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [147]:
v = np.random.random(10)
v.sort()
v

Sorted array:
[0.01262717 0.04893178 0.17467309 0.19153745 0.19664952 0.38427277
 0.52251175 0.85925308 0.92267673 0.96042759]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [154]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [169]:
A = np.random.randint(1,3,3)
print(A)
B = np.random.randint(1,3,3)
print(B)
np.array_equal(A, B)

[2 2 1]
[1 2 1]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [171]:
a = np.random.random(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [173]:
matr10x2 = np.random.random((10,2))
print(matr10x2)
x = matr10x2[:, 0]
y = matr10x2[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
t = np.arctan2(y, x)
print(r)
print(t)

[[0.90315882 0.21116289]
 [0.74077204 0.13634091]
 [0.44918718 0.44841916]
 [0.14854029 0.50258813]
 [0.1457517  0.69086742]
 [0.58448791 0.30785346]
 [0.61492493 0.44403012]
 [0.90767371 0.13645467]
 [0.15339343 0.2642608 ]
 [0.29650771 0.93381749]]
[0.92751583 0.75321448 0.63470376 0.52407923 0.70607461 0.66060569
 0.75848231 0.91787333 0.30555411 0.97976116]
[0.22967904 0.18201542 0.78454253 1.28342641 1.36287611 0.48478368
 0.62539704 0.14921707 1.04486668 1.26334271]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [174]:
arr = np.random.randint(10, 99, 10)
print(arr)
print('max: ', arr[arr.argmax()])
arr[arr.argmax()] = 0
print(arr)

[26 81 14 84 15 65 34 60 45 50]
max:  84
[26 81 14  0 15 65 34 60 45 50]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [176]:
arr = np.zeros((5, 5), [('x', float), ('y', float)])
print(arr)
arr['x'], arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(arr)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [177]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[-6.84466862e+07, -2.83295481e+06,  1.14507599e+06,
         1.46866490e+06, -1.91222163e+04],
       [-2.92038956e+04, -1.28174697e+05,  4.22863866e+07,
        -2.68757145e+06, -3.62825594e+04],
       [-2.80657097e+05,  3.97855694e+05,  4.30887087e+07,
        -9.55086611e+04, -1.26001410e+05],
       [-2.37177378e+06, -5.31968909e+05,  3.46199114e+04,
        -9.84675879e+04, -1.04280689e+04],
       [-4.84800528e+04,  7.41344008e+06, -1.51037106e+04,
        -2.52673806e+05, -1.84340544e+04]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [181]:
print('min, max for int8, int32, int64')
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
print('min, max for float32, float64')
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

min, max for int8, int32, int64
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
min, max for float32, float64
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [183]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [186]:
sc = np.arange(10)
print(sc)
v = np.random.uniform(0,10)
print(v)
index = (np.abs(sc - v)).argmin()
print(sc[index])

[0 1 2 3 4 5 6 7 8 9]
7.962864655696479
8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [18]:
arr = np.zeros(10, [ ('position', [ ('x', float, (1,)),
                                    ('y', float, (1,))
                                  ]),
                     ('color',    [ ('r', float, (1,)),
                                    ('g', float, (1,)),
                                    ('b', float, (1,))
                                  ])
                   ])
arr

array([(([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.])),
       (([0.], [0.]), ([0.], [0.], [0.]))],
      dtype=[('position', [('x', '<f8', (1,)), ('y', '<f8', (1,))]), ('color', [('r', '<f8', (1,)), ('g', '<f8', (1,)), ('b', '<f8', (1,))])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [189]:
v = np.random.randint(1, 10, (100,2))
x, y = np.atleast_2d(v[:,0], v[:,1])
D = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
print(D)

[[0.         8.48528137 8.06225775 ... 8.06225775 5.         5.        ]
 [8.48528137 0.         2.23606798 ... 5.38516481 3.60555128 3.60555128]
 [8.06225775 2.23606798 0.         ... 7.21110255 4.         4.        ]
 ...
 [8.06225775 5.38516481 7.21110255 ... 0.         4.47213595 4.47213595]
 [5.         3.60555128 4.         ... 4.47213595 0.         0.        ]
 [5.         3.60555128 4.         ... 4.47213595 0.         0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [194]:
fl_arr = (np.random.rand(10)*100).astype(np.float32)
int_arr = fl_arr.view(np.int32)
print(fl_arr)
int_arr[:] = fl_arr
print(int_arr)

[89.19145  62.23909  72.82169  78.1954   20.590557  4.619917 41.549717
 41.147205 44.394783 54.426376]
[89 62 72 78 20  4 41 41 44 54]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [19]:
from io import StringIO
s = StringIO('''1, 2, 3,  4,  5
                6,  ,  ,  7,  8
                 ,  , 9, 10, 11
''')
arr = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [20]:
arr = np.arange(2,25,3)
print(arr)
for index, item in np.ndenumerate(arr):
  print("index:", index, "item:", item)

[ 2  5  8 11 14 17 20 23]
index: (0,) item: 2
index: (1,) item: 5
index: (2,) item: 8
index: (3,) item: 11
index: (4,) item: 14
index: (5,) item: 17
index: (6,) item: 20
index: (7,) item: 23


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [22]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x * x + y * y)
sigma = 1.0
mu = 0.0
g = np.exp(-((d - mu) ** 2 / ( 2.0 * sigma ** 2)))
print("2D Gaussian-like array:")
print(g)

2D Gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [23]:
n = 10
p = 3
arr2d = np.zeros((n, n))
np.put(arr2d, np.random.choice(range(n * n), p, replace=False), 1)
print (arr2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [27]:
matr = np.random.rand(5, 10)
print(matr)
m = matr - matr.mean(axis=1, keepdims=True)
print(m)
print(matr)

[[0.29592864 0.09304136 0.64597965 0.97883716 0.69365579 0.45160173
  0.02211076 0.14358298 0.03912815 0.70609686]
 [0.09924858 0.64124198 0.52026127 0.90326985 0.81777016 0.81707811
  0.18131528 0.58975901 0.79184146 0.65758702]
 [0.40159243 0.03516283 0.61596027 0.2879737  0.62916089 0.66734894
  0.44842238 0.29963227 0.71411272 0.7825795 ]
 [0.50959106 0.75753681 0.73325776 0.83070381 0.98972617 0.41353802
  0.26175695 0.64576241 0.90330399 0.65543119]
 [0.88508806 0.7156171  0.92584321 0.21203322 0.44764806 0.36299758
  0.84629451 0.80507528 0.12520701 0.67222707]]
[[-0.11106767 -0.31395495  0.23898334  0.57184085  0.28665948  0.04460542
  -0.38488555 -0.26341333 -0.36786816  0.29910056]
 [-0.50268869  0.03930471 -0.081676    0.30133258  0.21583288  0.21514084
  -0.42062199 -0.01217826  0.18990419  0.05564975]
 [-0.08660216 -0.45303177  0.12776568 -0.20022089  0.1409663   0.17915435
  -0.03977221 -0.18856232  0.22591813  0.29438491]
 [-0.16046975  0.08747599  0.06319695  0.16064299

#### 59. How to sort an array by the nth column? (★★☆)

In [29]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[6 7 7]
 [3 0 0]
 [3 6 3]]
[[3 0 0]
 [3 6 3]
 [6 7 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [30]:
arr = np.random.randint(0,3,(4,10))
print(arr)
print((~arr.any(axis=0)).any())

[[2 1 1 1 0 1 1 2 2 2]
 [1 1 1 1 0 1 2 2 0 1]
 [0 0 1 0 2 0 1 1 0 1]
 [0 2 1 0 1 0 0 0 1 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [33]:
arr = np.random.uniform(0,1,10)
print(arr)
a = 0.5
n = arr.flat[np.abs(arr - a).argmin()]
print(n)

[0.22212343 0.7344624  0.07010126 0.05014152 0.93896526 0.27504562
 0.95943144 0.10053066 0.89639039 0.9555698 ]
0.275045617311654


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [34]:
arr1 = np.arange(3).reshape(3, 1)
arr2 = np.arange(3).reshape(1, 3)
iter = np.nditer([arr1, arr2, None])
for i, j, k in iter: k[...] = i + j
print(iter.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [36]:
class namedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")
arr = namedArray(np.arange(10), "named array")
print (arr.name, arr)

named array [0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [37]:
v = np.ones(10)
i = np.random.randint(0, len(v), 20)
v += np.bincount(i, minlength = len(Z))
print(v)

[4. 2. 2. 3. 3. 4. 1. 3. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [40]:
X = [1, 2, 3, 4, 5, 6]
I = [0, 3, 9, 3, 4, 1]
F = np.bincount(X, I)
print(F)

[0. 0. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [41]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [45]:
arr = np.random.randint(0,10,(3,4,3,4))
sum = arr.sum(axis=(-2,-1))
print(sum)
sum = arr.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[67 51 48 53]
 [55 59 57 65]
 [50 51 41 60]]
[[67 51 48 53]
 [55 59 57 65]
 [50 51 41 60]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [46]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.74455277 0.52109244 0.43764918 0.474951   0.60134376 0.48254096
 0.53982496 0.66493136 0.59811298 0.4641262 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [47]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.14729813, 0.57346484, 1.63893671, 0.53182313, 1.49768662])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [49]:
v = np.array([1, 2, 3, 4, 5])
nv = 3
v0 = np.zeros(len(v) + (len(v)-1)*(nv))
v0[::nv+1] = v
print(v0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [50]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [53]:
arr = np.arange(16).reshape(4,4)
print(arr)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [58]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 51) ( 0, 84) ( 3, 11) ( 3, 50) (10, 68) (10, 86) (11, 13) (11, 50)
 (11, 73) (13, 73) (17, 97) (23, 63) (23, 73) (47, 48) (47, 51) (48, 51)
 (50, 66) (50, 90) (51, 84) (56, 58) (56, 67) (58, 67) (63, 73) (64, 74)
 (64, 82) (66, 90) (68, 86) (74, 82) (97, 97)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [59]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [64]:
def moving_average(a, n = 3) :
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.arange(20)
print(moving_average(arr, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [65]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [68]:
arr = np.random.randint(0, 2, 100)
np.logical_not(arr, out=arr)
arr = np.random.uniform(-1.0, 1.0, 100)
np.negative(arr, out=arr)

array([-0.69285588, -0.02404443, -0.69362305, -0.28285558,  0.3772247 ,
       -0.57256652,  0.09694373,  0.86164138, -0.86267412, -0.58836837,
        0.41236274,  0.89355829,  0.2049518 , -0.05537322,  0.67515833,
       -0.45733852,  0.11633951,  0.21943194,  0.89683426, -0.91335976,
       -0.22924914, -0.31797868,  0.52468893,  0.20836697, -0.95789988,
       -0.4994505 , -0.06588612, -0.48979123, -0.56128339, -0.22065996,
        0.03305725, -0.94925439,  0.79764734, -0.25190774,  0.04895622,
       -0.06606926,  0.29800981, -0.3834735 , -0.24272309, -0.98220612,
        0.14847917, -0.38856477, -0.66720552, -0.90641497, -0.1337703 ,
       -0.87748355, -0.97658659,  0.05943134, -0.46408352, -0.11461601,
        0.87245427,  0.39196259,  0.60986506, -0.87887972,  0.72793112,
        0.36066017, -0.40880807,  0.66872402,  0.49418728,  0.02523742,
        0.79334369,  0.45109606, -0.49762718,  0.90303617,  0.82823784,
        0.85741169,  0.15553002,  0.744756  , -0.70008101, -0.67

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [71]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.78830463  0.86434634  6.34419812 12.97127555  0.25404325 12.96609317
 16.71356901  9.48978509  4.80983092  1.105739  ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [80]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print('Z: ', Z)
print('R: ', R)

Z:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
R:  [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [81]:
matr = np.random.randint(1,10,(5,5))
U, S, V = np.linalg.svd(matr) 
rank = np.sum(S > 1e-10)
print(rank)

5


#### 83. How to find the most frequent value in an array?

In [85]:
arr = np.random.randint(1,10,10)
print(arr)
print(np.bincount(arr).argmax())

[4 4 4 6 6 7 7 8 6 9]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [90]:
matr10x10 = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (matr10x10.shape[0]-3)
j = 1 + (matr10x10.shape[1]-3)
C = np.lib.stride_tricks.as_strided(matr10x10, shape=(i, j, n, n), strides=matr10x10.strides + matr10x10.strides)
print(C)

[[[[1 0 2]
   [4 1 3]
   [1 4 4]]

  [[0 2 1]
   [1 3 1]
   [4 4 4]]

  [[2 1 4]
   [3 1 4]
   [4 4 2]]

  [[1 4 1]
   [1 4 1]
   [4 2 4]]

  [[4 1 4]
   [4 1 1]
   [2 4 3]]

  [[1 4 1]
   [1 1 0]
   [4 3 4]]

  [[4 1 1]
   [1 0 3]
   [3 4 2]]

  [[1 1 0]
   [0 3 2]
   [4 2 2]]]


 [[[4 1 3]
   [1 4 4]
   [4 2 4]]

  [[1 3 1]
   [4 4 4]
   [2 4 3]]

  [[3 1 4]
   [4 4 2]
   [4 3 0]]

  [[1 4 1]
   [4 2 4]
   [3 0 4]]

  [[4 1 1]
   [2 4 3]
   [0 4 3]]

  [[1 1 0]
   [4 3 4]
   [4 3 2]]

  [[1 0 3]
   [3 4 2]
   [3 2 2]]

  [[0 3 2]
   [4 2 2]
   [2 2 0]]]


 [[[1 4 4]
   [4 2 4]
   [1 0 3]]

  [[4 4 4]
   [2 4 3]
   [0 3 0]]

  [[4 4 2]
   [4 3 0]
   [3 0 4]]

  [[4 2 4]
   [3 0 4]
   [0 4 4]]

  [[2 4 3]
   [0 4 3]
   [4 4 3]]

  [[4 3 4]
   [4 3 2]
   [4 3 0]]

  [[3 4 2]
   [3 2 2]
   [3 0 2]]

  [[4 2 2]
   [2 2 0]
   [0 2 4]]]


 [[[4 2 4]
   [1 0 3]
   [4 0 1]]

  [[2 4 3]
   [0 3 0]
   [0 1 0]]

  [[4 3 0]
   [3 0 4]
   [1 0 3]]

  [[3 0 4]
   [0 4 4]
   [0 3 3]]

  [[0 4 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [94]:
p = 10
n = 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [96]:
arr16x16 = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(arr16x16, np.arange(0, arr16x16.shape[0], k), axis=0), np.arange(0, arr16x16.shape[1], k), axis=1)
print (arr16x16)
print (S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [101]:
arr = np.random.randint(1, 10, 10)
print(arr)
n = 3
print (arr[np.argsort(arr)[-n:]])

[1 5 3 9 1 2 7 6 5 9]
[7 9 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [104]:
arr = np.array([(1, 2, 3),
              (4, 5, 6)])
arr_rec = np.core.records.fromarrays(arr.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(arr_rec)

[(b'1', 2., 3) (b'4', 5., 6)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [109]:
Z = np.random.rand(int(5e7))

print(np.power(Z, 3))

print(Z*Z*Z)

[5.20028149e-01 2.48682729e-02 1.39583722e-04 ... 7.91257960e-01
 9.35803163e-01 3.02007299e-02]
[5.20028149e-01 2.48682729e-02 1.39583722e-04 ... 7.91257960e-01
 9.35803163e-01 3.02007299e-02]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [114]:
A = np.random.randint(0,10,(8,3))
B = np.random.randint(0,10,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print("Rows: \n", rows)

[[6 4 1]
 [1 8 9]
 [5 0 0]
 [4 7 8]
 [7 8 9]
 [0 0 6]
 [0 8 5]
 [4 2 1]]
[[3 7]
 [0 4]]
Rows: 
 [2 3 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [117]:
matr10x3 = np.random.randint(0,2,(10,3))
print(matr10x3)
uneq = matr10x3[matr10x3.max(axis=1) != matr10x3.min(axis=1),:]
print('rows with unequal values: ', uneq)

[[0 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 1]
 [0 0 0]
 [1 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [1 0 0]]
rows with unequal values:  [[0 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [1 0 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [118]:
v = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
matr = np.unpackbits(v[:, np.newaxis], axis=1)
print(v)
print(matr)

[  0   1   2   3  15  16  32  64 128]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [129]:
arr = np.random.randint(0,2,(6,3))
print(arr)
T = np.ascontiguousarray(arr).view(np.dtype((np.void, arr.dtype.itemsize * arr.shape[1])))
_, idx = np.unique(T, return_index=True)
uniq = arr[idx]
print("Unique rows: \n", uniq)

[[0 0 0]
 [1 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 1 0]]
Unique rows: 
 [[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [134]:
A = np.random.randint(1, 10, 5)
B = np.random.randint(1, 10, 5)
print(A)
print(B)
print('Sum A: ', np.einsum('i->', A))
print('Mul: ', np.einsum('i,i->i', A, B))
print('Inner: ', np.einsum('i,i', A, B))
print('Outer: ', np.einsum('i,j', A, B))

[4 2 6 9 2]
[1 1 3 9 1]
Sum A:  23
Mul:  [ 4  2 18 81  2]
Inner:  107
Outer:  [[ 4  4 12 36  4]
 [ 2  2  6 18  2]
 [ 6  6 18 54  6]
 [ 9  9 27 81  9]
 [ 2  2  6 18  2]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randint(1, 10, 10) 
N = 10
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)